### ISSUE TITLE
Separate kill rankings

### ISSUE THREAD

**Issue by Unfellowed** [LinGe515/L4D2_LinGe_VScripts#1]
Which line should I fix to separate the SI and CI kill rankings? Thank you!
![Screenshot (883)](https://user-images.githubusercontent.com/115072518/234853702-afde631d-a206-4fb0-8e66-f6e85484c174.png)

**Comment by Lin515** [comment]
In the next update, column alignment will be supported, but all columns are in the same player order.

**Comment by Lin515** [comment]
Column alignment mode has been supported. To switch, you need to modify the configuration file `HUD.hurt.HUDRankMode = 1`. Can display up to 8 player, but I recommend not exceeding 4 in the settings.
