### ISSUE TITLE
关闭了HUD，但仍会干扰SM插件的HUD

### ISSUE THREAD

**Issue by oblivcheck** [LinGe515/L4D2_LinGe_VScripts#2]
我在专用服务器上使用[击杀伤害统计](https://steamcommunity.com/sharedfiles/filedetails/?id=2819660601)与[基础库](https://steamcommunity.com/sharedfiles/filedetails/?id=2819659703).

将后者与[SpeakingList](https://github.com/accelerator74/sp-plugins/tree/2ce16cfc3abd673ced16e98cf15bc16a7d0a4d11/l4d2_SpeakingList)或[l4d2_voiceviewer](https://github.com/oblivcheck/l4d2_plugins/tree/master/l4d2_voiceviewer)一起使用会导致Sourcemod插件的HUD完全消失或者闪烁.

**ems/linge/config_XXXX.tbl**
```
{
        MoreSI = {
                sinoci = false
                sionly = [
                ]
                sibase = 0
                enabled = true
                initDelay = 5
                simin = 0
                sitime = 4
                siauto = 1
        }
        Admin = {
                takeOverAdminSystem = false
                enabled = false
                adminsFile = "linge/admins_simple.ini"
        }
        HUD = {
                position = {
                        players_x = 0
                        time_x = 0.75
                        hostname_x = 0.4
                        players_y = 0
                        time_y = 0
                        rank_y = 0.025
                        rank_x = 0
                        hostname_y = 0
                }
                playersStyle = {
                        versus = "生还:{sur,human}  VS  特感:{spe,human}"
                        coop = "活跃:{sur,human}  摸鱼:{ob}  空位:{vac}  存活特感:{spe,alive}  本局特感击杀:{ksi}"
                }
                textHeight2 = 0.026
                HUDShow = {
                        hostname = false
                        players = false
                        all = false
                        time = false
                        versusNoHUDRank = true
                }
                hurt = {
                        HUDRank = 4
                        teamHurtInfo = 2
                        chatStyle2 = "特感:{ksi}({si}伤害) 小僵尸:{kci} 黑枪:{atk} 被黑:{vct} <- {name}"
                        rankColumnAlign = [
                                {
                                        width = 0.1
                                        style = "{ksi}/{o_ksi}"
                                        title = "特感"
                                }
                                {
                                        width = 0.1
                                        style = "{kci}/{o_kci}"
                                        title = "丧尸"
                                }
                                {
                                        width = 0.1
                                        style = "{state}"
                                        title = "血量状态"
                                }
                                {
                                        width = 0.7
                                        style = "[{rank}] {name}"
                                        title = "玩家"
                                }
                        ]
                        chatTeamHurtPraise = "大家真棒，没有友伤的世界达成了~"
                        HUDRankMode = 0
                        rankCompact = {
                                style = "[{rank}] {ksi}/{kci} <- {name}({state})"
                                title = "特感/丧尸击杀："
                        }
                        chatVctMaxStyle = "都欺负我:{name}({hurt})"
                        chatRank = 4
                        chatAtkMaxStyle = "队友鲨手:{name}({hurt})"
                        autoPrint = 180
                        discardLostRound = false
                        HUDRankShowBot = false
                        tankHurt = {
                                style = "[{rank}] {hurt} <- {name}"
                                title = "本次击杀了共 {count} 只 Tank，伤害贡献如下"
                        }
                }
        }
        Base = {
                isShowTeamChange = false
                recordPlayerInfo = false
        }
}
```

```
ems
ems/_vslib_global_cache.tbl
ems/linge
ems/linge/config_XXXX.tbl
ems/linge/admins_simple.ini
ems/linge/playerslist.tbl
```

**Comment by Lin515** [comment]
965b5b9
已更新，再次开启房间运行 MOD 后，配置文件中会多出一个 HUD.HUDShow.CompatVSLibHud 的选项，默认为 true。将其与 HUD.HUDShow.all 都设置为 false，应该就不会和插件的 HUD 冲突了。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月13日 07:18 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [Lin515/L4D2_LinGe_VScripts] 关闭了HUD，但是会干扰SM插件的HUD (Issue #2) |

我在专用服务器上使用击杀伤害统计与基础库.

将后者与SpeakingList或l4d2_voiceviewer一起使用会导致Sourcemod插件的HUD完全消失或者闪烁.

ems/linge/config_XXXX.tbl

{
        MoreSI = {
                sinoci = false
                sionly = [
                ]
                sibase = 0
                enabled = true
                initDelay = 5
                simin = 0
                sitime = 4
                siauto = 1
        }
        Admin = {
                takeOverAdminSystem = false
                enabled = false
                adminsFile = "linge/admins_simple.ini"
        }
        HUD = {
                position = {
                        players_x = 0
                        time_x = 0.75
                        hostname_x = 0.4
                        players_y = 0
                        time_y = 0
                        rank_y = 0.025
                        rank_x = 0
                        hostname_y = 0
                }
                playersStyle = {
                        versus = "生还:{sur,human}  VS  特感:{spe,human}"
                        coop = "活跃:{sur,human}  摸鱼:{ob}  空位:{vac}  存活特感:{spe,alive}  本局特感击杀:{ksi}"
                }
                textHeight2 = 0.026
                HUDShow = {
                        hostname = false
                        players = false
                        all = false
                        time = false
                        versusNoHUDRank = true
                }
                hurt = {
                        HUDRank = 4
                        teamHurtInfo = 2
                        chatStyle2 = "特感:{ksi}({si}伤害) 小僵尸:{kci} 黑枪:{atk} 被黑:{vct} <- {name}"
                        rankColumnAlign = [
                                {
                                        width = 0.1
                                        style = "{ksi}/{o_ksi}"
                                        title = "特感"
                                }
                                {
                                        width = 0.1
                                        style = "{kci}/{o_kci}"
                                        title = "丧尸"
                                }
                                {
                                        width = 0.1
                                        style = "{state}"
                                        title = "血量状态"
                                }
                                {
                                        width = 0.7
                                        style = "[{rank}] {name}"
                                        title = "玩家"
                                }
                        ]
                        chatTeamHurtPraise = "大家真棒，没有友伤的世界达成了~"
                        HUDRankMode = 0
                        rankCompact = {
                                style = "[{rank}] {ksi}/{kci} <- {name}({state})"
                                title = "特感/丧尸击杀："
                        }
                        chatVctMaxStyle = "都欺负我:{name}({hurt})"
                        chatRank = 4
                        chatAtkMaxStyle = "队友鲨手:{name}({hurt})"
                        autoPrint = 180
                        discardLostRound = false
                        HUDRankShowBot = false
                        tankHurt = {
                                style = "[{rank}] {hurt} <- {name}"
                                title = "本次击杀了共 {count} 只 Tank，伤害贡献如下"
                        }
                }
        }
        Base = {
                isShowTeamChange = false
                recordPlayerInfo = false
        }
}

ems
ems/_vslib_global_cache.tbl
ems/linge
ems/linge/config_XXXX.tbl
ems/linge/admins_simple.ini
ems/linge/playerslist.tbl

**Comment by Lin515** [comment]
965b5b9

**Comment by oblivcheck** [comment]
没有问题了！
