### ISSUE TITLE
能否添加配置文件热重载功能

### ISSUE THREAD

**Issue by TunArund** [LinGe515/L4D2_LinGe_VScripts#4]
只有!save
没有!reload
btw脚本写的非常好，不用sourcemod一个个收集了

**Comment by Lin515** [comment]
在最开始写的时候没考虑热重载的功能，这个功能的实现和整套MOD的启动运行框架相关，重读一次配置文件等于把整套mod的运行重置。如果是从一开始就打算实现这个功能，会挺好实现的，现在想实现的话，需要大改代码，所以不会做了。
另外游戏里每成功过关或过关失败，游戏重新开始就会重载脚本读取一次配置文件，而且配置文件应该没有什么需要频繁游戏中修改的东西，需要游戏中修改的项目我都提供了指令，所以这个功能我觉得是用处不大的。

**Comment by TunArund** [comment]
好的，换图或过关能重新加载就足够了
